version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'krns'
    open-pull-requests-limit: 10
  - package-ecosystem: 'mix'
    directory: '/'
    schedule:
      interval: 'daily'
    insecure-external-code-execution: allow
    reviewers:
      - 'krns'
    open-pull-requests-limit: 10
  - package-ecosystem: 'mix'
    directory: '/demo/'
    schedule:
      interval: 'daily'
    insecure-external-code-execution: allow
    reviewers:
      - 'krns'
    open-pull-requests-limit: 10
  - package-ecosystem: 'npm'
    directory: '/demo/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'krns'
    open-pull-requests-limit: 10
