version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'krns'
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: -1
    open-security-pull-requests-limit: -1
  - package-ecosystem: 'mix'
    directory: '/'
    schedule:
      interval: 'daily'
    insecure-external-code-execution: allow
    reviewers:
      - 'krns'
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: -1
    open-security-pull-requests-limit: -1
  - package-ecosystem: 'mix'
    directory: '/demo/'
    schedule:
      interval: 'daily'
    insecure-external-code-execution: allow
    reviewers:
      - 'krns'
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: -1
    open-security-pull-requests-limit: -1
  - package-ecosystem: 'npm'
    directory: '/demo/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'krns'
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: -1
    open-security-pull-requests-limit: -1
