blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/naymspace/backpex/discussions
    about: Please ask and answer questions here.
  - name: Feature Requests
    url: https://github.com/naymspace/backpex/discussions/categories/ideas
    about: Share ideas for new features here.
