name: CI

on:
  push:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_TESTING: ${{ github.repository }}/testing
  IMAGE_NAME_RUNTIME: ${{ github.repository }}/runtime

jobs:
  test:
    name: "Test backpex"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.15.7']
        erlang: ['26.1.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang }}
          elixir-version: ${{ matrix.elixir }}

      - name: Restore deps and _build cache
        uses: actions/cache@v1
        with:
          path: |
            deps
            _build
            .mix
          key: deps-${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            deps-${{ runner.os }}-mix-

      - name: Install dependencies
        run: |
          mix local.hex --force --if-missing
          mix local.rebar --force --if-missing
          mix deps.get
      
      - name: Run tests
        run: |
          mix test
      
      - name: Check formatting
        run: |
          mix format --check-formatted
      
      - name: Compile with warnings as errors
        run: |
          mix compile --warnings-as-errors --force

      - name: Dialyzer
        run: |
          mix dialyzer --force-check

      - name: Credo
        run: |
          mix credo

      - name: Sobelow
        run: |
          mix sobelow --config

      - name: Deps Unused
        run: |
          mix deps.unlock --check-unused

      - name: Deps Audit 
        run: |
          mix deps.audit
      
      - name: Gettext Check
        run: |
          mix gettext.extract --check-up-to-date

  build-demo-testing:
    name: "Build and push demo testing image"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_TESTING }}

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: builder
          build-args: |
            MIX_ENV=test
    outputs:
      image: ${{ steps.meta.outputs.tags }}

  test-demo:
    needs: build-demo-testing
    name: "Lint demo"
    runs-on: ubuntu-latest
  
    steps:
      - name: "Run linter inside demo testing image"
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ needs.build-demo-testing.outputs.image }}
          run: |
            cd /opt/app
            yarn lint:mix

      # - name: Run hex info
      #   run: |
      #     mix hex.info

      # - name: Debug
      #   run: |
      #     pwd
      #     ls -la

      # - name: Run linters
      #   run: |
      #     cd /opt/app
      #     yarn lint
      #     yarn lint:mix
      #     yarn lint:dialyzer
      #     yarn lint:credo
      #     yarn lint:sobelow
      #     yarn lint:style
      #     yarn lint:standard
      #     yarn lint:deps-unused
      #     yarn lint:gettext

  build-demo-runtime:
    name: "Build and push demo runtime image"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_RUNTIME }}

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: runtime
          build-args: |
            MIX_ENV=prod